// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATnjGFW7E-V9_gSxC_8eYcKLjWScjcjGU',
    appId: '1:926739474102:android:f8090db40b350cf52e2817',
    messagingSenderId: '926739474102',
    projectId: 'monapp-1aa68',
    databaseURL: 'https://monapp-1aa68-default-rtdb.firebaseio.com',
    storageBucket: 'monapp-1aa68.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCInGASZhoYaOMEMy7jwQKxnA5Ham1-GJo',
    appId: '1:926739474102:ios:9d999c3085b1533d2e2817',
    messagingSenderId: '926739474102',
    projectId: 'monapp-1aa68',
    databaseURL: 'https://monapp-1aa68-default-rtdb.firebaseio.com',
    storageBucket: 'monapp-1aa68.firebasestorage.app',
    iosBundleId: 'com.yourname.skeleton',
  );
}
